server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: submit-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hdv-submit-service
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver